# Generated by Django 3.0 on 2020-04-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fundraise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('goal', models.FloatField()),
                ('raised', models.FloatField()),
                ('skillcount', models.BooleanField(default=False)),
            ],
        ),
    ]
